name: "Continuous Integration"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Checkout code

      - uses: actions/setup-python@v4
      - name: Set up Python
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -r requirements-dev.txt -r requirements-tes.txt

      - name: Run tests
        env:
          MODE: "github actions"
        run: |
          make model-test
          make api-test
      
      - uses: actions/checkout@v4
        run: docker build . --file Dockerfile --tag acalmo/latam-challenge:latest
